### ISSUE TITLE
New Admin-Ui Icons

### ISSUE THREAD

**Issue by efjacobson** [triniti/admin-ui-plugin-js#124]
New Icons for copy/pasting block content
- clipboard-paste
- clipboard-copied

these blocks dont have a dedicated icon:
- youtube playlist - currently use playlist
- soundcloud audio - already have soundcloud logo
- spotify track - will add spotify logo

**Comment by mgollnick** [comment]
![image](https://user-images.githubusercontent.com/11724358/61091807-6bf5d280-a3f8-11e9-834b-797c694cd301.png)
