### ISSUE TITLE
Move css for Nav and Navbar component locally

### ISSUE THREAD

**Issue by mgollnick** [triniti/admin-ui-plugin-js#21]

**Comment by mgollnick** [comment]
@weiwang314 this is ready for testing. There is talk of moving the nav to the left in a future branch so I can fix anything I missed then.

**Comment by weiwang314** [comment]
@mgollnick I fixed the demo/navbar and the navbar tests based on what we have now. 
But reactstrap's new version updated navbar components a little, and fixed some issue, could you take a look at their site to check whether its worth to update ours or not once you get time?

**Comment by mgollnick** [comment]
@weiwang314 this one is ready for testing. I just fixed the example page and cleaned out some unused code.
