### ISSUE TITLE
Update Icon Component to dynamically load svg files from folder

### ISSUE THREAD

**Issue by mgollnick** [triniti/admin-ui-plugin-js#36]

**Comment by mgollnick** [comment]
@weiwang314 This is ready for testing. I was able to dynamically load different svg files into the img tag. I wasn't sure how to test if the icon exists first.  If they spell it wrong or the icon is removed, then the page breaks.  Sort of like if you mess up a component reference.

**Comment by weiwang314** [comment]
not sure this is the convenient way to use icons since it is weird to save all icons wihtin the component folder. Works for now. 
I also add a feature the icon component now also accept a regular src prop, which can render the icon svg from anywhere
