### ISSUE TITLE
MainContent bug: cannot pass className prop

### ISSUE THREAD

**Issue by efjacobson** [triniti/admin-ui-plugin-js#51]
Currently the MainContent component is not accepting the className prop. This would be useful for edge cases where we need to style it. For example, if there is a small amount of text in the block editor (ie https://cms.tmzlabs.com/news/articles/18ad9d49-de88-4821-85e7-e8c038c5abea/story/edit) the popup inline toolbar is being cut off because MainContent has overflow auto/hidden where it needs to have visible.

**Comment by mgollnick** [comment]
I will update this on the bootstrap-update branch.
