### ISSUE TITLE
TabNav bug: dies with <2 children

### ISSUE THREAD

**Issue by efjacobson** [triniti/admin-ui-plugin-js#56]
may not be that big of a deal since presumably TabNav will always have 2+ children, but if it does not ie

```
<TabNav>
  <RouterLink navTab to="/news/articles/create/story">Story</RouterLink>
</TabNav>
```

it will choke with the warning `Uncaught TypeError: children.map is not a function`

this could theoretically happen if there were conditional tabs - ie a screen always has one tab, but due to a flag (hasSeo, for instance) the second possible tab is not included.

**Comment by gdbrown** [comment]
invalid, TabNav itself has died.
